Iter9
Zrossiz/go-metrics pull request #11
Opened 2024-08-28 20:31 UTC by Zrossiz

2024-09-02 19:44 UTC, nburunova requested changes

2024-09-02 19:44 UTC, nburunova commented on internal/agent/http/send/send.go
> +			log.Println("unsupported metric type for metric:", metrics[i].Name)
continue

2024-09-02 19:44 UTC, nburunova commented on internal/agent/http/send/send.go
> +			log.Println("failed to create HTTP request:", err)
continue.
Я бы тут советовала то, что в цикле, выделить в отдельную функцию \ функции, и на err != nil делать return. Сейчас тело цикла слишком большое  и ты забываешь continue. C return такое не реже случается, обычно не забывают про возврат из функции в случае ошибки

2024-09-02 19:44 UTC, nburunova commented on internal/agent/http/send/send.go
> +func GzipMetrics(metrics []types.Metric, addr string) []types.Metric {
фунцкия называется GzipMetrics, но она еще и http.Post делает. Несоотвествие имени функции фактическому действию, которое она совершает. И еще фукнция должна выполнять одно действие. Раздели эту функцию на две: gzip metric и send metric

2024-09-02 19:44 UTC, nburunova commented on internal/server/config/config.go
> +	fmt.Println("addr: ", RunAddr)
тут нужно логгером залогировать а не fmt

2024-09-02 19:44 UTC, nburunova commented on internal/server/config/config.go
> +			sugar.Panic("env store interval have invalid value")
в принципе сойдет, но я бы рекомендовала все panic, fatal явно делать в func main(), рядовые функции не должны прекращать работу сервиса, они должны возвращать ошибку, а уже main решит, нужно делать panic или что-то другое

2024-09-02 19:44 UTC, nburunova commented on internal/server/services/get/get.go
>  		http.Error(rw, "metric not found", 404)
используй значение http.StatusNotFound вместо того, чтобы явно 404 отправлять, так будет выглядеть аккуратнее

2024-09-02 19:44 UTC, nburunova commented on internal/server/services/update/update.go
> +	fmt.Println("TYPE: ", typeMetric)
тут логгер не получится подтянуть для логирования вместо fmt?

2024-09-02 19:44 UTC, nburunova commented on internal/server/storage/fileStorage/fileStorage.go
> +			logger.Sugar().Warnf("error to parse metric: %s", s.Name)
тут надо понять, действительно ли в случае ошибки нам можно пропустить метрику? Или всё же вернуть ошибку из update?

2024-09-02 19:44 UTC, nburunova commented on internal/server/storage/memStorage/memStorage.go
>  	}
возможно ли такое, что сразу несколько горутин будут использовать memstorage? если да, то Metrics следует прикрыть мьютексом sync.RWMutex, чтобы избежать race condition

2024-09-07 14:53 UTC, Bazys approved these changes
пара мелких вопросов, но щас уже не буду заворачивать, пора дальше двигаться, очень надеюсь по ходу исправишь

2024-09-07 14:53 UTC, Bazys commented on internal/server/app/main.go
> +func StartServer() error {
а зачем возвращать ошибку, если ты ни разу ее не проверяешь?

2024-09-07 14:53 UTC, Bazys commented on internal/server/app/main.go
> +	r.Use(func(next http.Handler) http.Handler {
обертка ради обертки?
а просто юзать request.WithLogs?

2024-09-07 14:53 UTC, Bazys commented on internal/agent/app/app.go
> +	var counter int64 = 0
нет необходимости явно указывать 0 - дефолтное значение инта - 0

2024-09-07 21:35 UTC, merged