Iter13
Zrossiz/go-metrics pull request #15
Opened 2024-09-15 10:06 UTC by Zrossiz

2024-09-19 07:13 UTC, Bazys requested changes
парочка вопросов

2024-09-19 07:13 UTC, Bazys commented on internal/server/service/metric.go
> +	dbConn  *pgxpool.Pool
а зачем это, ты ни разу не использовал

2024-09-19 07:13 UTC, Bazys commented on internal/server/transport/http/handler/handler.go
> +func (m *MetricHandler) PingDB(rw http.ResponseWriter, r *http.Request) {
Параметр функции, названный `r`, не используется в теле функции. В Go, если определили параметр в функции, но не использовали его внутри, это считается неоптимальным стилем, поскольку параметр занимает место в сигнатуре функции и может сбивать с толку при чтении кода.
В данном случае, есть два возможных решения:
1. **Удаление параметра:** Если параметр `r` действительно не нужен для работы функции, его можно просто удалить из сигнатуры функции. Это делает код чище и проще для понимания.
2. **Переименование в `_`:** Если параметр не используется, но его наличие обязательно по какой-то причине (например, для соответствия интерфейсу или для использования в будущем), его можно переименовать в `_`. В Go, символ `_` используется для игнорирования переменной. Переменные, именованные как `_`, не обязаны быть использованы, т.е. не будет копирования неиспользуемого значения внутрь функции. Это позволяет сохранить сигнатуру функции неизменной, но явно указывает на то, что данный параметр в настоящее время не используется и избежать лишнего использования памяти.

2024-09-19 07:13 UTC, Bazys commented on internal/server/service/metric.go
> +	var newBody []dto.PostMetricDto
Преаллоцируй слайс. Тебе известен его будущий размер. как то так:
```go
newBody := make([]dto.PostMetricDto, 0, len(body))
```
Таки образом повышаем производительность Go-приложения за счет минимизации динамического выделения памяти во время выполнения. Предварительное аллоцирование слайсов в Go может значительно сократить накладные расходы на увеличение слайса по мере добавления элементов, что предполагает выделение новой памяти и копирование существующих элементов в новое пространство памяти.
В Go, когда вы заранее знаете количество элементов, которые будет вмещать слайс, вы можете использовать функцию `make`, чтобы указать его начальную длину и объем. Такая практика особенно полезна для слайсов, размер которых увеличивается по мере выполнения программы, поскольку избавляет Go от необходимости автоматически изменять размер слайса каждый раз, когда в него добавляется элемент после превышения его емкости.
Предварительное аллокация выгодна для производительности, особенно в сценариях с большими массивами данных или высокопроизводительными задачами, потому что она уменьшает количество выделений памяти и связанные с этим затраты на управление памятью, например сборку мусора.
Для более подробного тзучения оптимизации производительности кода Go и управления памятью, включая эффективное использование срезов и функции `make`, посмотри на таких ресурсам, как:
1. [The Impact of Preallocating Slice Memory in Golang (Continued)](https://oilbeater.com/en/2024/03/04/golang-slice-performance-cont/)
2. [Optimize by pre-allocating slice](https://www.programming-books.io/essential/go/optimize-by-pre-allocating-slice-ee6501b596c9446da8b82e4ed35454a6)

2024-09-19 07:13 UTC, Bazys commented on internal/agent/http/send/send.go
> +		if err != nil {
каскад ифчиов в го принято менять на switch
https://go.dev/doc/effective_go#switch

2024-09-19 07:13 UTC, Bazys commented on internal/server/transport/http/handler/handler.go
> +	json.NewEncoder(rw).Encode(response)
а ошибку проверить?

2024-09-19 07:13 UTC, Bazys commented on internal/server/storage/filestorage/filestorage.go
> +			f.SetCounter(metricDTO)
ошибку проверить?

2024-09-19 08:24 UTC, Zrossiz commented on internal/server/service/metric.go
> +	dbConn  *pgxpool.Pool
MetricService.storage использовал

2024-09-19 08:33 UTC, Zrossiz commented on internal/agent/http/send/send.go
> +		if err != nil {
по логике приложения это можно сделать только в таком виде

		if err != nil {
			log.Printf("Failed to send request: %v\n", err)
		} else {
			switch resp.StatusCode {
			case 200:
				return nil
			default:
				log.Printf("Failed to send request: status code %d\n", resp.StatusCode)
			}
		}

2024-09-20 19:37 UTC, Bazys commented on internal/server/service/metric.go
> +	dbConn  *pgxpool.Pool
dbConn  *pgxpool.Pool - нигде не используется

2024-09-20 20:39 UTC, Bazys approved these changes
во всем мржно найти компромис

2024-09-20 20:39 UTC, Bazys commented on internal/server/storage/dbstorage/dbstorage.go
> +func (d *DBStorage) Save(filePath string) error {
тоже неиспользуемый параметр

2024-09-20 20:39 UTC, Bazys commented on internal/agent/http/send/send.go
> +		if err != nil {
switch {
  case err != nil:

  case resp.StatusCode == 200 : 

  default:  
}

2024-09-21 02:03 UTC, merged