Iter5
Zrossiz/go-metrics pull request #7
Opened 2024-08-12 18:36 UTC by Zrossiz

2024-08-14 15:42 UTC, Bazys requested changes
парочка вопросов.
Но самое главное - это почитай в сторону DependencyInjection
1.  https://github.com/evrone/go-clean-template?tab=readme-ov-file#dependency-injection
2. https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/dependency-injection

2024-08-14 15:42 UTC, Bazys commented on internal/agent/app/app.go
> +			counter += 1
```suggestion
			counter++
```

2024-08-14 15:42 UTC, Bazys commented on internal/server/services/get/get.go
> +func GetHTMLPageMetric(rw http.ResponseWriter, r *http.Request) {
снаружи эта функция выглядит как `get.GetHTMLPageMetric` - масло масляное. рекомендую полумать над неймингом.
1. https://go.dev/blog/package-names
2. https://go.dev/doc/effective_go#names
3. https://google.github.io/styleguide/go/decisions.html

2024-08-14 15:42 UTC, Bazys commented on internal/agent/services/collector/collector.go
> +	metrics = append(metrics, types.Metric{
`append` может принимать цепочку.
но ябы подумал над циклом

2024-08-14 15:42 UTC, Bazys commented on internal/server/storage/memStorage/memStorage.go
> +func SetGauge(name string, value float64) bool {
подумай над интерффейсным подходом.
потом сложно будет писать тесты

2024-08-18 13:16 UTC, Bazys submitted a review, later dismissed
убрать рефлефксию

2024-08-18 13:16 UTC, Bazys commented on internal/agent/services/collector/collector.go
> +		switch fieldValue.Kind() {
switch s := memStats.(type) 
давай всё таки обойдемся без рефлексии

2024-08-23 16:44 UTC, nburunova approved these changes

2024-08-24 10:45 UTC, merged